Added player death coordinates message upon death
Artillex-Studios/AxGraves pull request #7
Opened 2024-01-11 06:00 UTC by LhAlant

Added a message in chat when a player dies.
Fixes #2 
It can be configured to be a message to every player, only the player who died or to not message anyone.

2024-01-11 16:41 UTC, AverageGithub requested changes
We really appreciate your contribution! I've requested some changes, if that's not a problem for you 😄

2024-01-11 16:41 UTC, AverageGithub commented on src/main/java/com/artillexstudios/axgraves/grave/Grave.java
> +                p.sendMessage(String.format("%s died at X:%.2f Y:%.2f Z:%.2f", player.getName(), location.getX(), location.getY(), location.getZ()));
Could you make the message configurable in the messages.yml? (And use the prefix) Also, we would probably want the name of the world in which this happened. Also, we'd want a list of worlds in which if the player dies the messages aren't sent. 

Possibly, we'd even want a range for this message, for example: 
-1: all worlds 
0: only the player's world
other: the range in which we gather the players to send the message to

2024-01-11 16:41 UTC, AverageGithub commented on src/main/java/com/artillexstudios/axgraves/grave/Grave.java
> +            player.sendMessage(String.format("You died at X:%.2f Y:%.2f Z:%.2f", location.getX(), location.getY(), location.getZ()));
Please add this into messages.yml aswell (and use the prefix)

2024-01-11 16:41 UTC, AverageGithub commented on src/main/java/com/artillexstudios/axgraves/grave/Grave.java
> +        if (CONFIG.getBoolean("global-announce-death-coordinates", true)){
This should default to false

2024-01-11 16:41 UTC, AverageGithub commented on src/main/java/com/artillexstudios/axgraves/grave/Grave.java
> +        } else if (CONFIG.getBoolean("private-announce-death-coordinates", true)){
Default to false aswell(, and this would change to a regular if statement if you were to add the configurable range)

2024-01-11 16:41 UTC, AverageGithub commented on src/main/resources/config.yml
> +private-announce-death-coordinates: true
Should probably default to true, to keep things consistent between versions, and prevent unexpected messages being sent after the plugin updates

2024-01-11 16:41 UTC, AverageGithub commented on src/main/resources/config.yml
> +version: 5
We'd want to bump the config version, so the new things get added to the already existing configs

2024-01-11 19:48 UTC, LhAlant commented
I added the requested changes

2024-01-20 20:07 UTC, LhAlant commented
I updated the config.yml version because release 1.5.0 changed it

2024-04-14 17:32 UTC, svaningelgem commented
Is this branch still active? Because I'm looking for a similar feature as well.

2024-04-19 02:24 UTC, LhAlant commented
> Is this branch still active? Because I'm looking for a similar feature as well.

No, I just added this feature because I wanted it in a server I made. I'm just waiting for them to deny/merge this branch.

2024-04-19 04:09 UTC, svaningelgem commented
Thanks for the reply, but I ended up forking the Graves plugin of Ranull [here](https://github.com/AvarionMC/graves). That had everything (and more) but the gravestone.

2024-11-08 13:20 UTC, closed without merging

2024-11-08 13:20 UTC, BenceX100 commented
Closing this as this as there is already a similiar feature like this for a while now.